function expenseSheet(){const active=typeof profileName==='function'?profileName():'';return `<div class="sheetBack" id="overlay"><div class="sheet"><h2>הוצאה חדשה</h2><label>סכום</label><input id="amount" class="amountField" inputmode="decimal" placeholder="0.00"><label>איפה?</label><input id="merchant" placeholder="למשל: רמי לוי"><label>קטגוריה</label><select id="category">${state.categories.map(c=>`<option value="${c.id}">${c.group} · ${c.name}</option>`).join('')}</select><div class="two"><div><label>מי שילם?</label><select id="person"><option ${active==='יהונתן'?'selected':''}>יהונתן</option><option ${active==='שני'?'selected':''}>שני</option></select></div><div><label>אמצעי תשלום</label><select id="payment"><option>אשראי</option><option>מזומן</option><option>Bit</option><option>העברה</option><option>אחר</option></select></div></div><button class="save" id="saveExpense">שמור הוצאה</button></div></div>`}
function editSheet(c){return `<div class="sheetBack" id="overlay"><div class="sheet"><h2>עריכת ${c.name}</h2><label>תקציב חודשי</label><input id="editBudget" type="number" class="amountField" value="${c.budget}"><label>גמישות</label><select id="editFlex"><option value="fixed" ${c.flex==='fixed'?'selected':''}>קשיח</option><option value="medium" ${c.flex==='medium'?'selected':''}>בינוני</option><option value="high" ${c.flex==='high'?'selected':''}>גמיש</option></select><label>סוג</label><select id="editVis"><option value="visible" ${c.visibility==='visible'?'selected':''}>הוצאה גלויה</option><option value="hidden" ${c.visibility==='hidden'?'selected':''}>רזרבה / חבויה</option></select><button class="save" id="saveCategory">שמור שינויים</button></div></div>`}
function openSheet(html){document.body.insertAdjacentHTML('beforeend',html);document.getElementById('overlay').onclick=e=>{if(e.target.id==='overlay')e.currentTarget.remove()}}

function bindActions(){
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{mobileTab=b.dataset.tab;render()});
  document.querySelectorAll('[data-dtab]').forEach(b=>b.onclick=()=>{desktopTab=b.dataset.dtab;render()});
  document.querySelectorAll('.mProfile').forEach(b=>b.onclick=()=>cloudReady&&typeof accountSheet==='function'?accountSheet():null);

  document.querySelectorAll('[data-action="add"]').forEach(b=>b.onclick=()=>{openSheet(expenseSheet());document.getElementById('saveExpense').onclick=async()=>{const amount=Number(document.getElementById('amount').value),merchant=document.getElementById('merchant').value.trim();if(!amount||!merchant)return alert('צריך סכום ובית עסק');const t={id:crypto.randomUUID(),month:state.month,date:new Date().toISOString(),merchant,amount,categoryId:document.getElementById('category').value,person:document.getElementById('person').value,payment:document.getElementById('payment').value};const btn=document.getElementById('saveExpense');btn.disabled=true;btn.textContent='שומר...';try{if(cloudReady&&typeof cloudAddTransaction==='function')await cloudAddTransaction(t);else{state.transactions.unshift(t);saveState()}document.getElementById('overlay')?.remove()}catch(e){btn.disabled=false;btn.textContent='שמור הוצאה';alert('לא הצלחתי לשמור: '+e.message)}}});
  document.querySelectorAll('[data-action="scan"]').forEach(b=>b.onclick=()=>alert('צילום קבלה ו-AI יתחברו בשלב הבא. כרגע ניתן להזין ידנית.'));
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const c=state.categories.find(x=>x.id===b.dataset.edit);openSheet(editSheet(c));document.getElementById('saveCategory').onclick=async()=>{c.budget=Number(document.getElementById('editBudget').value)||0;c.flex=document.getElementById('editFlex').value;c.visibility=document.getElementById('editVis').value;try{if(cloudReady&&typeof cloudUpdateCategory==='function')await cloudUpdateCategory(c);else saveState();document.getElementById('overlay')?.remove()}catch(e){alert('לא הצלחתי לשמור: '+e.message)}}});
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('למחוק את ההוצאה?'))return;try{if(cloudReady&&typeof cloudDeleteTransaction==='function')await cloudDeleteTransaction(b.dataset.del);else{state.transactions=state.transactions.filter(t=>t.id!==b.dataset.del);saveState()}}catch(e){alert('לא הצלחתי למחוק: '+e.message)}});
  document.querySelectorAll('[data-income]').forEach(i=>i.onchange=async()=>{const x=state.incomes.find(x=>x.id===i.dataset.income);x.budget=Number(i.value)||0;try{if(cloudReady&&typeof cloudUpdateIncome==='function')await cloudUpdateIncome(x);else saveState()}catch(e){alert('לא הצלחתי לשמור: '+e.message)}});
  document.querySelectorAll('[data-setting="savings"]').forEach(i=>i.onchange=()=>{state.household.monthlySavingsTarget=Number(i.value)||0;saveState()});
  document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=async()=>{if(!confirm('לאפס רק את העסקאות? התקציב יישאר.'))return;if(cloudReady)return alert('איפוס ענן מלא יתווסף בהמשך. אפשר למחוק עסקאות בנפרד כרגע.');state.transactions=[];saveState()});
}

if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{});if(window.caches)caches.keys().then(keys=>keys.filter(k=>k.startsWith('kamaout')).forEach(k=>caches.delete(k))).catch(()=>{})}
initCloud();
