function expenseSheet(prefill={}){const active=typeof profileName==='function'?profileName():'';return `<div class="sheetBack" id="overlay"><div class="sheet"><h2>${prefill.receiptUrl?'אישור קבלה':'הוצאה חדשה'}</h2>${prefill.receiptUrl?`<img src="${prefill.receiptUrl}" style="width:100%;max-height:220px;object-fit:contain;border-radius:14px;background:#f5f7fa">`:''}<label>סכום</label><input id="amount" class="amountField" inputmode="decimal" placeholder="0.00" value="${prefill.amount||''}"><label>איפה?</label><input id="merchant" placeholder="למשל: רמי לוי" value="${prefill.merchant||''}"><label>קטגוריה</label><select id="category">${state.categories.map(c=>`<option value="${c.id}" ${prefill.categoryId===c.id?'selected':''}>${c.group} · ${c.name}</option>`).join('')}</select><div class="two"><div><label>מי שילם?</label><select id="person"><option ${(prefill.person||active)==='יהונתן'?'selected':''}>יהונתן</option><option ${(prefill.person||active)==='שני'?'selected':''}>שני</option></select></div><div><label>אמצעי תשלום</label><select id="payment"><option ${prefill.payment==='אשראי'?'selected':''}>אשראי</option><option ${prefill.payment==='מזומן'?'selected':''}>מזומן</option><option ${prefill.payment==='Bit'?'selected':''}>Bit</option><option ${prefill.payment==='העברה'?'selected':''}>העברה</option><option ${prefill.payment==='אחר'?'selected':''}>אחר</option></select></div></div><button class="save" id="saveExpense">שמור הוצאה</button></div></div>`}
function transactionEditSheet(t){return `<div class="sheetBack" id="overlay"><div class="sheet"><h2>עריכת הוצאה</h2><label>סכום</label><input id="txAmount" class="amountField" type="number" step="0.01" value="${t.amount}"><label>בית עסק</label><input id="txMerchant" value="${t.merchant}"><label>קטגוריה</label><select id="txCategory">${state.categories.map(c=>`<option value="${c.id}" ${t.categoryId===c.id?'selected':''}>${c.group} · ${c.name}</option>`).join('')}</select><div class="two"><div><label>מי שילם?</label><select id="txPerson"><option ${t.person==='יהונתן'?'selected':''}>יהונתן</option><option ${t.person==='שני'?'selected':''}>שני</option></select></div><div><label>אמצעי תשלום</label><select id="txPayment"><option ${t.payment==='אשראי'?'selected':''}>אשראי</option><option ${t.payment==='מזומן'?'selected':''}>מזומן</option><option ${t.payment==='Bit'?'selected':''}>Bit</option><option ${t.payment==='העברה'?'selected':''}>העברה</option><option ${t.payment==='אחר'?'selected':''}>אחר</option></select></div></div><div class="two"><button class="save" id="saveTx">שמור שינויים</button><button class="save" id="deleteTx" style="background:#fff0f0;color:#c33">מחק הוצאה</button></div></div></div>`}
function editSheet(c){return `<div class="sheetBack" id="overlay"><div class="sheet"><h2>עריכת ${c.name}</h2><label>תקציב חודשי</label><input id="editBudget" type="number" class="amountField" value="${c.budget}"><label>גמישות</label><select id="editFlex"><option value="fixed" ${c.flex==='fixed'?'selected':''}>קשיח</option><option value="medium" ${c.flex==='medium'?'selected':''}>בינוני</option><option value="high" ${c.flex==='high'?'selected':''}>גמיש</option></select><label>סוג</label><select id="editVis"><option value="visible" ${c.visibility==='visible'?'selected':''}>הוצאה גלויה</option><option value="hidden" ${c.visibility==='hidden'?'selected':''}>רזרבה / חבויה</option></select><button class="save" id="saveCategory">שמור שינויים</button></div></div>`}
function openSheet(html){document.body.insertAdjacentHTML('beforeend',html);document.getElementById('overlay').onclick=e=>{if(e.target.id==='overlay')e.currentTarget.remove()}}
function guessReceipt(text){const clean=(text||'').replace(/,/g,'.');const nums=[...clean.matchAll(/(?:₪|ILS|NIS|TOTAL|סה.?כ)?\s*(\d{1,5}(?:\.\d{1,2})?)/gi)].map(m=>Number(m[1])).filter(n=>n>0&&n<100000);const amount=nums.length?Math.max(...nums):'';const firstLine=(text||'').split(/\n/).map(s=>s.trim()).find(s=>s.length>2&&!/^\d/.test(s))||'';let cat=state.categories.find(c=>c.key==='food')?.id||state.categories[0]?.id;if(/דלק|fuel|yellow|paz|sonol/i.test(text))cat=state.categories.find(c=>c.key==='transport')?.id||cat;if(/פארם|pharm|super-pharm|be|health/i.test(text))cat=state.categories.find(c=>c.key==='health-hidden')?.id||cat;return {amount,merchant:firstLine.slice(0,60),categoryId:cat}}
async function startReceiptScan(){const input=document.createElement('input');input.type='file';input.accept='image/*';input.capture='environment';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const waiting=document.createElement('div');waiting.className='sheetBack';waiting.id='scanWait';waiting.innerHTML='<div class="sheet"><h2>קורא את הקבלה...</h2><p>מעלה תמונה ומנסה לזהות סכום ובית עסק</p></div>';document.body.appendChild(waiting);const receiptUrl=await cloudUploadReceipt(file);let text='';try{const {createWorker}=await import('https://esm.sh/tesseract.js@5');const worker=await createWorker('eng+heb');const r=await worker.recognize(file);text=r.data.text||'';await worker.terminate()}catch(e){console.warn('OCR failed',e)}document.getElementById('scanWait')?.remove();const guess=guessReceipt(text);openSheet(expenseSheet({...guess,receiptUrl,ocrText:text}));document.getElementById('saveExpense').onclick=()=>saveExpenseFromSheet({receiptUrl,ocrText:text})}catch(e){document.getElementById('scanWait')?.remove();alert('לא הצלחתי לסרוק את הקבלה: '+e.message)}};input.click()}
async function saveExpenseFromSheet(extra={}){const amount=Number(document.getElementById('amount').value),merchant=document.getElementById('merchant').value.trim();if(!amount||!merchant)return alert('צריך סכום ובית עסק');const t={id:crypto.randomUUID(),month:state.month,date:new Date().toISOString(),merchant,amount,categoryId:document.getElementById('category').value,person:document.getElementById('person').value,payment:document.getElementById('payment').value,...extra};const btn=document.getElementById('saveExpense');btn.disabled=true;btn.textContent='שומר...';try{if(cloudReady&&typeof cloudAddTransaction==='function')await cloudAddTransaction(t);else{state.transactions.unshift(t);saveState()}document.getElementById('overlay')?.remove()}catch(e){btn.disabled=false;btn.textContent='שמור הוצאה';alert('לא הצלחתי לשמור: '+e.message)}}

function bindActions(){
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{mobileTab=b.dataset.tab;render()});document.querySelectorAll('[data-dtab]').forEach(b=>b.onclick=()=>{desktopTab=b.dataset.dtab;render()});document.querySelectorAll('.mProfile').forEach(b=>b.onclick=()=>cloudReady&&typeof accountSheet==='function'?accountSheet():null);
  document.querySelectorAll('[data-action="add"]').forEach(b=>b.onclick=()=>{openSheet(expenseSheet());document.getElementById('saveExpense').onclick=()=>saveExpenseFromSheet()});
  document.querySelectorAll('[data-action="scan"]').forEach(b=>b.onclick=()=>startReceiptScan());
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const c=state.categories.find(x=>x.id===b.dataset.edit);openSheet(editSheet(c));document.getElementById('saveCategory').onclick=async()=>{c.budget=Number(document.getElementById('editBudget').value)||0;c.flex=document.getElementById('editFlex').value;c.visibility=document.getElementById('editVis').value;try{if(cloudReady&&typeof cloudUpdateCategory==='function')await cloudUpdateCategory(c);else saveState();document.getElementById('overlay')?.remove()}catch(e){alert('לא הצלחתי לשמור: '+e.message)}}});
  document.querySelectorAll('[data-edit-tx]').forEach(b=>b.onclick=()=>{const t=state.transactions.find(x=>x.id===b.dataset.editTx);if(!t)return;openSheet(transactionEditSheet(t));document.getElementById('saveTx').onclick=async()=>{const updated={...t,amount:Number(document.getElementById('txAmount').value),merchant:document.getElementById('txMerchant').value.trim(),categoryId:document.getElementById('txCategory').value,person:document.getElementById('txPerson').value,payment:document.getElementById('txPayment').value};if(!updated.amount||!updated.merchant)return alert('צריך סכום ובית עסק');try{await cloudUpdateTransaction(updated);document.getElementById('overlay')?.remove()}catch(e){alert('לא הצלחתי לשמור: '+e.message)}};document.getElementById('deleteTx').onclick=async()=>{if(!confirm('למחוק את ההוצאה?'))return;try{await cloudDeleteTransaction(t.id);document.getElementById('overlay')?.remove()}catch(e){alert('לא הצלחתי למחוק: '+e.message)}}});
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('למחוק את ההוצאה?'))return;try{if(cloudReady&&typeof cloudDeleteTransaction==='function')await cloudDeleteTransaction(b.dataset.del);else{state.transactions=state.transactions.filter(t=>t.id!==b.dataset.del);saveState()}}catch(e){alert('לא הצלחתי למחוק: '+e.message)}});
  document.querySelectorAll('[data-income]').forEach(i=>i.onchange=async()=>{const x=state.incomes.find(x=>x.id===i.dataset.income);x.budget=Number(i.value)||0;try{if(cloudReady&&typeof cloudUpdateIncome==='function')await cloudUpdateIncome(x);else saveState()}catch(e){alert('לא הצלחתי לשמור: '+e.message)}});
  document.querySelectorAll('[data-setting="savings"]').forEach(i=>i.onchange=()=>{state.household.monthlySavingsTarget=Number(i.value)||0;saveState()});document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=async()=>{if(!confirm('לאפס רק את העסקאות? התקציב יישאר.'))return;if(cloudReady)return alert('איפוס ענן מלא יתווסף בהמשך. אפשר למחוק עסקאות בנפרד כרגע.');state.transactions=[];saveState()});
}
if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{});if(window.caches)caches.keys().then(keys=>keys.filter(k=>k.startsWith('kamaout')).forEach(k=>caches.delete(k))).catch(()=>{})}initCloud();
