let sb=null,cloudReady=false,currentHouseholdId=null,realtimeChannel=null;
const SIMPLE_PROFILES=[{id:'yehonatan',name:'יהונתן'},{id:'shani',name:'שני'}];
let currentProfileId=localStorage.getItem('kamaout-last-profile')||'';
async function ensureClient(){const cfg=window.KAMAOUT_CONFIG||{};if(!cfg.supabaseUrl||!cfg.supabaseKey)return false;if(!sb){const mod=await import('https://esm.sh/@supabase/supabase-js@2');sb=mod.createClient(cfg.supabaseUrl,cfg.supabaseKey)}return true}
function profileName(id=currentProfileId){return SIMPLE_PROFILES.find(p=>p.id===id)?.name||''}
function profilePhoto(id){return window.KAMAOUT_AVATARS?.[id]||''}
function profilePhotoHtml(id,cls='profilePhoto'){const url=profilePhoto(id);return url?`<img class="${cls}" src="${url}" alt="${profileName(id)}">`:`<span class="${cls}">${id==='shani'?'ש':'י'}</span>`}
function setProfile(id){currentProfileId=id;localStorage.setItem('kamaout-last-profile',id)}
function profilePicker(){document.getElementById('app').innerHTML=`<div class="authShell"><div class="authCard profilePickerCard"><div class="authBrand">KamaOut</div><div class="authTag">מי משתמש עכשיו?</div><div class="profileChoices">${SIMPLE_PROFILES.map(p=>`<button class="profileChoice" data-profile="${p.id}">${profilePhotoHtml(p.id,'profileChoicePhoto')}<strong>${p.name}</strong><small>המשך כ${p.name}</small></button>`).join('')}</div><div class="profileHint">נזכור את הבחירה במכשיר הזה</div></div></div>`;document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=async()=>{setProfile(b.dataset.profile);await loadCloudState()})}
async function loadCloudState(){const {data:hid,error:hidErr}=await sb.rpc('get_simple_household_id');if(hidErr||!hid){console.error(hidErr);return alert('לא הצלחתי לטעון את משק הבית')}currentHouseholdId=hid;const [{data:house},{data:inc},{data:cats},{data:tx}]=await Promise.all([sb.from('households').select('id,name').eq('id',hid).single(),sb.from('income_sources').select('*').eq('household_id',hid).order('sort_order'),sb.from('categories').select('*').eq('household_id',hid).order('sort_order'),sb.from('transactions').select('*').eq('household_id',hid).order('transaction_date',{ascending:false}).order('created_at',{ascending:false})]);state={month:new Date().toISOString().slice(0,7),household:{name:house?.name||'משפחת דמרי',currency:'ILS',monthlySavingsTarget:1000},incomes:(inc||[]).map(x=>({id:x.id,name:x.name,budget:Number(x.monthly_budget)})),categories:(cats||[]).map(c=>({id:c.id,key:c.key,group:c.group_name,name:c.name,budget:Number(c.monthly_budget),flex:c.flexibility,visibility:c.visibility,alertAt:c.alert_at==null?undefined:Number(c.alert_at)})),transactions:(tx||[]).map(t=>({id:t.id,month:t.transaction_date.slice(0,7),date:t.transaction_date,merchant:t.merchant||'',amount:Number(t.amount),categoryId:t.category_id,person:t.payer_name||profileName(t.entered_by_profile),payment:t.payment_method||'',enteredBy:t.entered_by_profile||'',receiptUrl:t.receipt_url||'',ocrText:t.receipt_ocr_text||''}))};cloudReady=true;render();subscribeRealtime()}
function subscribeRealtime(){if(realtimeChannel)sb.removeChannel(realtimeChannel);realtimeChannel=sb.channel('kamaout-household').on('postgres_changes',{event:'*',schema:'public',table:'transactions',filter:`household_id=eq.${currentHouseholdId}`},()=>loadCloudState()).on('postgres_changes',{event:'*',schema:'public',table:'categories',filter:`household_id=eq.${currentHouseholdId}`},()=>loadCloudState()).on('postgres_changes',{event:'*',schema:'public',table:'income_sources',filter:`household_id=eq.${currentHouseholdId}`},()=>loadCloudState()).subscribe()}
async function cloudAddTransaction(t){const {error}=await sb.from('transactions').insert({household_id:currentHouseholdId,created_by:null,category_id:t.categoryId,amount:t.amount,merchant:t.merchant,payer_name:t.person,payment_method:t.payment,transaction_date:new Date(t.date).toISOString().slice(0,10),entered_by_profile:currentProfileId,receipt_url:t.receiptUrl||null,receipt_ocr_text:t.ocrText||null});if(error)throw error;await loadCloudState()}
async function cloudUpdateTransaction(t){const {error}=await sb.from('transactions').update({category_id:t.categoryId,amount:t.amount,merchant:t.merchant,payer_name:t.person,payment_method:t.payment,transaction_date:new Date(t.date).toISOString().slice(0,10)}).eq('id',t.id);if(error)throw error;await loadCloudState()}
async function cloudUpdateCategory(c){const {error}=await sb.from('categories').update({monthly_budget:c.budget,flexibility:c.flex,visibility:c.visibility}).eq('id',c.id);if(error)throw error;await loadCloudState()}
async function cloudDeleteTransaction(id){const {error}=await sb.from('transactions').delete().eq('id',id);if(error)throw error;await loadCloudState()}
async function cloudUpdateIncome(x){const {error}=await sb.from('income_sources').update({monthly_budget:x.budget}).eq('id',x.id);if(error)throw error;await loadCloudState()}
async function cloudUploadReceipt(file){const ext=(file.name?.split('.').pop()||'jpg').toLowerCase();const path=`${currentHouseholdId}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('receipts').upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(error)throw error;const {data}=sb.storage.from('receipts').getPublicUrl(path);return data.publicUrl}
function accountSheet(){openSheet(`<div class="sheetBack" id="overlay"><div class="sheet accountSheet"><h2>מי משתמש עכשיו?</h2><div class="accountInfo">${profilePhotoHtml(currentProfileId,'accountAvatar')}<div><strong>${profileName()}</strong><small>${state.household.name}</small></div></div><div class="profileChoices compact">${SIMPLE_PROFILES.map(p=>`<button class="profileChoice ${p.id===currentProfileId?'selected':''}" data-switch-profile="${p.id}">${profilePhotoHtml(p.id,'profileChoicePhoto')}<strong>${p.name}</strong></button>`).join('')}</div></div></div>`);document.querySelectorAll('[data-switch-profile]').forEach(b=>b.onclick=()=>{setProfile(b.dataset.switchProfile);document.getElementById('overlay')?.remove();render()})}
async function initCloud(){const ok=await ensureClient();if(!ok){cloudReady=false;render();return false}if(!currentProfileId)return profilePicker();await loadCloudState();return true}
