const DEFAULT_STATE={month:'2026-09',household:{name:'משפחת דמרי',currency:'ILS',monthlySavingsTarget:1000},incomes:[{id:'inc1',name:'יהונתן – שכר נטו',budget:26000},{id:'inc2',name:'שני – הכנסה חלקית',budget:5000},{id:'inc3',name:'קצבאות ילדים',budget:380},{id:'inc4',name:'הכנסה נוספת',budget:0}],categories:[{id:'edu-niv',key:'edu-niv',group:'חינוך',name:'ניב – גן',budget:4320,flex:'fixed',visibility:'visible'},{id:'edu-peleg-after',key:'edu-peleg-after',group:'חינוך',name:'פלג – צהרון',budget:1190,flex:'fixed',visibility:'visible'},{id:'edu-peleg-school',key:'edu-peleg-school',group:'חינוך',name:'פלג – בית ספר',budget:600,flex:'fixed',visibility:'visible'},{id:'edu-activities',key:'edu-activities',group:'חינוך',name:'חוגים ופעילויות',budget:1500,flex:'fixed',visibility:'visible'},{id:'food',key:'food',group:'מזון',name:'מזון וסופר',budget:5500,flex:'high',visibility:'visible',alertAt:5500},{id:'arnona',key:'arnona',group:'חשבונות',name:'ארנונה ומים',budget:850,flex:'fixed',visibility:'visible'},{id:'electric',key:'electric',group:'חשבונות',name:'חשמל',budget:500,flex:'fixed',visibility:'visible',alertAt:700},{id:'comms',key:'comms',group:'חשבונות',name:'אינטרנט + טלפונים',budget:400,flex:'fixed',visibility:'visible'},{id:'hoa',key:'hoa',group:'חשבונות',name:'ועד בית',budget:300,flex:'fixed',visibility:'visible'},{id:'transport',key:'transport',group:'רכב',name:'דלק',budget:2700,flex:'high',visibility:'visible',alertAt:3000},{id:'transit-pass',key:'transit-pass',group:'תחבורה',name:'נסיעות וחופשי חודשי',budget:500,flex:'fixed',visibility:'visible'},{id:'insurance',key:'insurance',group:'ביטוחים',name:'ביטוחים',budget:1150,flex:'fixed',visibility:'visible'},{id:'leisure',key:'leisure',group:'פנאי',name:'פנאי ובידור',budget:700,flex:'high',visibility:'visible'},{id:'saving',key:'saving',group:'חיסכון',name:'חסכונות והשקעות',budget:1000,flex:'fixed',visibility:'visible'},{id:'housing',key:'housing',group:'דיור',name:'משכנתא + ביטוח דירה',budget:6300,flex:'fixed',visibility:'visible'},{id:'health-hidden',key:'health-hidden',group:'בריאות',name:'בריאות לא מכוסה',budget:300,flex:'fixed',visibility:'visible'},{id:'clothing-hidden',key:'clothing-hidden',group:'קניות',name:'ביגוד והנעלה',budget:400,flex:'high',visibility:'hidden'},{id:'gifts-hidden',key:'gifts-hidden',group:'מתנות ואירועים',name:'מתנות ואירועים',budget:300,flex:'medium',visibility:'hidden'},{id:'home-hidden',key:'home-hidden',group:'בית',name:'מוצרי בית והיגיינה',budget:200,flex:'medium',visibility:'hidden'},{id:'subscriptions-hidden',key:'subscriptions-hidden',group:'מנויים',name:'מנויים דיגיטליים',budget:150,flex:'fixed',visibility:'hidden'},{id:'repairs-hidden',key:'repairs-hidden',group:'בית',name:'תיקונים לא צפויים',budget:300,flex:'medium',visibility:'hidden'},{id:'vacation-hidden',key:'vacation-hidden',group:'חופשות',name:'חופשות',budget:500,flex:'fixed',visibility:'visible'}],transactions:[]};
let state=loadState(),mobileTab='home',desktopTab='overview',mobileFixedOpen=false;
const FIXED_CATEGORY_KEYS=new Set(['edu-niv','edu-peleg-after','edu-peleg-school','edu-activities','arnona','electric','comms','hoa','insurance','housing','subscriptions-hidden','saving','health-hidden','vacation-hidden','transit-pass']);
function clone(x){return JSON.parse(JSON.stringify(x))}
function loadState(){try{const x=localStorage.getItem('kamaout-v3-state');return x?JSON.parse(x):clone(DEFAULT_STATE)}catch{return clone(DEFAULT_STATE)}}
function saveState(){localStorage.setItem('kamaout-v3-state',JSON.stringify(state));render()}
function ils(n){return '₪'+Math.round(Number(n)||0).toLocaleString('he-IL')}
function categoryKey(c){return c?.key||c?.id||''}
function isFixedCategory(c){if(c?.trackingMode)return c.trackingMode==='automatic';return FIXED_CATEGORY_KEYS.has(categoryKey(c))}
function fixedCategories(){return state.categories.filter(isFixedCategory)}
function spendCategories(){return state.categories.filter(c=>!isFixedCategory(c))}
function rawActual(id){return state.transactions.filter(t=>t.categoryId===id&&t.month===state.month).reduce((s,t)=>s+Number(t.amount),0)}
function actual(id){const c=state.categories.find(x=>x.id===id);return c&&isFixedCategory(c)?Number(c.budget):rawActual(id)}
function fixedBudget(){return fixedCategories().reduce((s,c)=>s+Number(c.budget),0)}
function spendBudget(){return spendCategories().reduce((s,c)=>s+Number(c.budget),0)}
function spendActual(){const ids=new Set(spendCategories().map(c=>c.id));return state.transactions.filter(t=>t.month===state.month&&ids.has(t.categoryId)).reduce((s,t)=>s+Number(t.amount),0)}
function actualTotal(){return fixedBudget()+spendActual()}
function remainingSpend(){return Math.max(spendBudget()-spendActual(),0)}
function incomeBudget(){return state.incomes.reduce((s,x)=>s+Number(x.budget),0)}
function expenseBudget(){return state.categories.reduce((s,x)=>s+Number(x.budget),0)}
function hiddenBudget(){return state.categories.filter(x=>x.visibility==='hidden').reduce((s,x)=>s+Number(x.budget),0)}
function visibleBudget(){return expenseBudget()-hiddenBudget()}
function predictedBalance(){return incomeBudget()-expenseBudget()}
function pct(a,b){return b?Math.round(a/b*100):0}
function monthLabel(){const [y,m]=(state.month||new Date().toISOString().slice(0,7)).split('-').map(Number);return new Intl.DateTimeFormat('he-IL',{month:'long',year:'numeric'}).format(new Date(y,m-1,1))}
function monthRangeLabel(){const [y,m]=(state.month||new Date().toISOString().slice(0,7)).split('-').map(Number),last=new Date(y,m,0).getDate(),mn=new Intl.DateTimeFormat('he-IL',{month:'long'}).format(new Date(y,m-1,1));return `1–${last} ב${mn} ${y}`}
function groupData(){const m={};state.categories.forEach(c=>{m[c.group]??={budget:0,actual:0};m[c.group].budget+=Number(c.budget);m[c.group].actual+=actual(c.id)});return m}
function spendGroupData(){const m={};spendCategories().forEach(c=>{m[c.group]??={budget:0,actual:0};m[c.group].budget+=Number(c.budget);m[c.group].actual+=rawActual(c.id)});return m}
function alerts(){return spendCategories().map(c=>({c,a:rawActual(c.id),threshold:c.alertAt||c.budget,p:pct(rawActual(c.id),c.budget)})).filter(x=>x.a>x.threshold||x.p>=80).sort((a,b)=>b.p-a.p)}
function flexTotals(){const m={fixed:0,medium:0,high:0};state.categories.forEach(c=>m[c.flex]+=Number(c.budget));return m}
function txs(){return state.transactions.filter(t=>t.month===state.month).sort((a,b)=>new Date(b.date)-new Date(a.date))}
function flexLabel(f){return f==='fixed'?'קבוע':f==='medium'?'בינוני':'גמיש'}
function render(){document.getElementById('app').innerHTML=mobileView()+desktopView();bindActions()}
